/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/generate-types.ts.
 * JSON Schema 2020-12 files in packages/protocol/schemas are canonical.
 * Do not edit this file manually.
 */

/**
 * Handshake failures. The daemon sends at most one error response and then closes the connection.
 *
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "HandshakeErrorResponse".
 */
export type BridgeHandshakeErrorResponse =
  InvalidRequest | AuthenticationFailed | UnsupportedProtocolVersion;
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "ResponseId".
 */
export type ResponseId = JSONRPCRequestIdentifier | null;
/**
 * IDEBP request identifiers are non-empty strings or integers. Null is reserved for error responses whose request identifier could not be recovered.
 *
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "JsonRpcId".
 */
export type JSONRPCRequestIdentifier = string | number;
/**
 * A stable semantic version without prerelease or build metadata.
 *
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "ProtocolVersion".
 */
export type IDEBPProtocolVersion = string;
/**
 * This interface was referenced by `IDEBPHandshakeAuthentication`'s JSON-Schema
 * via the `definition` "token".
 *
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "Token".
 */
export type AuthenticationToken = string;
/**
 * An adapter exposes IDE operations. A consumer invokes daemon or adapter operations.
 *
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "SessionRole".
 */
export type IDEBPSessionRole = "adapter" | "consumer";
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "SessionId".
 */
export type SessionId = string;
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "AdapterId".
 */
export type AdapterId = string;
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "PositionEncoding".
 */
export type PositionEncoding = "utf-16" | "utf-8" | "utf-32";
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "Capability".
 */
export type Capability = AvailableCapability | UnavailableCapability;
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "Guarantee".
 */
export type Guarantee = "semantic" | "syntactic" | "anchored-text" | "raw-text";
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "Atomicity".
 */
export type Atomicity = "none" | "text-only" | "semantic";
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "Support".
 */
export type Support = "native" | "provider" | "adapter" | "unavailable";
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "WorkspaceId".
 */
export type WorkspaceId = string;
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "RootId".
 */
export type RootId = string;
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "ContentHash".
 */
export type ContentHash = string;
/**
 * What an edit plan performs. Every entry is a refactoring the IDE itself provides, prepared and applied through the same two-phase machinery, so a consumer reviews and consents to any of them identically.
 *
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "EditOperation".
 */
export type EditOperation =
  | "rename"
  | "reformat"
  | "optimizeImports"
  | "extractMethod"
  | "inline"
  | "move"
  | "changeSignature"
  | "quickFix";
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "PlanId".
 */
export type PlanId = string;
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "UndoTokenId".
 */
export type UndoTokenId = string;
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "SymbolHandleId".
 */
export type SymbolHandleId = string;
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "ReadinessState".
 */
export type ReadinessState = "initializing" | "indexing" | "ready" | "degraded" | "disconnected";
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "Progress".
 */
export type Progress =
  | {
      known: false;
    }
  | {
      known: true;
      percentage: number;
    };
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "SymbolKind".
 */
export type SymbolKind =
  | "file"
  | "module"
  | "namespace"
  | "package"
  | "class"
  | "method"
  | "property"
  | "field"
  | "constructor"
  | "enum"
  | "interface"
  | "function"
  | "variable"
  | "constant"
  | "string"
  | "number"
  | "boolean"
  | "array"
  | "object"
  | "key"
  | "null"
  | "enumMember"
  | "struct"
  | "event"
  | "operator"
  | "typeParameter"
  | "unknown";
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "SymbolReference".
 */
export type SymbolReference = SymbolReference1 & {
  handle?: SymbolHandle;
  locator?: SymbolLocator;
};
export type SymbolReference1 =
  | {
      handle: unknown;
    }
  | {
      locator: unknown;
    };
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "WorkspaceTrust".
 */
export type WorkspaceTrust = "trusted" | "untrusted" | "unknown";
/**
 * This interface was referenced by `IDEBPJSONRPCErrorResponse`'s JSON-Schema
 * via the `definition` "errorData".
 *
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "ErrorData".
 */
export type ErrorData =
  | GenericErrorData
  | IndexNotReadyErrorData
  | StaleDocumentErrorData
  | AmbiguousSymbolErrorData
  | PartialApplyErrorData;
/**
 * This interface was referenced by `IDEBPJSONRPCErrorResponse`'s JSON-Schema
 * via the `definition` "genericErrorCode".
 *
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "GenericErrorCode".
 */
export type GenericErrorCode =
  | "INVALID_REQUEST"
  | "UNSUPPORTED_PROTOCOL_VERSION"
  | "AUTHENTICATION_FAILED"
  | "WORKSPACE_NOT_FOUND"
  | "DOCUMENT_NOT_FOUND"
  | "ADAPTER_NOT_FOUND"
  | "ADAPTER_DISCONNECTED"
  | "CAPABILITY_UNAVAILABLE"
  | "STALE_SYMBOL"
  | "INVALID_IDENTIFIER"
  | "PRECONDITION_FAILED"
  | "PLAN_NOT_FOUND"
  | "PLAN_EXPIRED"
  | "PROVIDER_FAILED"
  | "TIMEOUT"
  | "CANCELLED"
  | "PERMISSION_DENIED"
  | "INTERNAL_ERROR";
/**
 * This interface was referenced by `IDEBPJSONRPCErrorResponse`'s JSON-Schema
 * via the `definition` "errorCode".
 *
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "ErrorCode".
 */
export type ErrorCode =
  | "INVALID_REQUEST"
  | "UNSUPPORTED_PROTOCOL_VERSION"
  | "AUTHENTICATION_FAILED"
  | "WORKSPACE_NOT_FOUND"
  | "DOCUMENT_NOT_FOUND"
  | "ADAPTER_NOT_FOUND"
  | "ADAPTER_DISCONNECTED"
  | "CAPABILITY_UNAVAILABLE"
  | "INDEX_NOT_READY"
  | "STALE_DOCUMENT"
  | "STALE_SYMBOL"
  | "AMBIGUOUS_SYMBOL"
  | "INVALID_IDENTIFIER"
  | "PRECONDITION_FAILED"
  | "PLAN_NOT_FOUND"
  | "PLAN_EXPIRED"
  | "PROVIDER_FAILED"
  | "TIMEOUT"
  | "CANCELLED"
  | "PERMISSION_DENIED"
  | "PARTIAL_APPLY"
  | "INTERNAL_ERROR";
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "BridgeGetStatusRequest".
 */
export type BridgeGetStatusRequest = AdministrationRequestBase & {
  method?: "bridge/getStatus";
};
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "BridgeListAdaptersRequest".
 */
export type BridgeListAdaptersRequest = AdministrationRequestBase & {
  method?: "bridge/listAdapters";
};
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "BridgeListSessionsRequest".
 */
export type BridgeListSessionsRequest = AdministrationRequestBase & {
  method?: "bridge/listSessions";
};
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "SymbolGetDefinitionRequest".
 */
export type SymbolGetDefinitionRequest = SymbolLookupRequestBase & {
  method?: "symbol/getDefinition";
};
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "SymbolGetReferencesRequest".
 */
export type SymbolGetReferencesRequest = SymbolLookupRequestBase & {
  method?: "symbol/getReferences";
};
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "SymbolGetImplementationsRequest".
 */
export type SymbolGetImplementationsRequest = SymbolLookupRequestBase & {
  method?: "symbol/getImplementations";
};
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "AdapterCapabilitiesChanged".
 */
export type AdapterCapabilitiesChangedNotification = NotificationBase & {
  method?: "adapter/capabilitiesChanged";
  params?: {
    adapterId: AdapterId;
    capabilities: Capabilities;
  };
};
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "AdapterDisconnected".
 */
export type AdapterDisconnectedNotification = NotificationBase & {
  method?: "adapter/disconnected";
  params?: {
    adapterId: AdapterId;
    reason: "shutdown" | "transport-lost" | "session-expired" | "error";
  };
};
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "WorkspaceOpened".
 */
export type WorkspaceOpenedNotification = NotificationBase & {
  method?: "workspace/opened";
  params?: {
    workspace: Workspace;
  };
};
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "WorkspaceClosed".
 */
export type WorkspaceClosedNotification = NotificationBase & {
  method?: "workspace/closed";
  params?: WorkspaceIdentityParams;
};
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "WorkspaceRootsChanged".
 */
export type WorkspaceRootsChangedNotification = NotificationBase & {
  method?: "workspace/rootsChanged";
  params?: {
    workspaceId: WorkspaceId;
    adapterId: AdapterId;
    /**
     * @minItems 1
     */
    roots: [WorkspaceRoot, ...WorkspaceRoot[]];
    workspaceEpoch: number;
  };
};
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "WorkspaceReadinessChanged".
 */
export type WorkspaceReadinessChangedNotification = NotificationBase & {
  method?: "workspace/readinessChanged";
  params?: {
    status: WorkspaceStatus;
  };
};
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "DocumentOpened".
 */
export type DocumentOpenedNotification = DocumentEventBase & {
  method?: "document/opened";
};
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "DocumentEventBase".
 */
export type DocumentEventBase = NotificationBase & {
  params?: {
    document: DocumentReference;
  };
};
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "DocumentChanged".
 */
export type DocumentChangedNotification = DocumentEventBase & {
  method?: "document/changed";
};
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "DocumentSaved".
 */
export type DocumentSavedNotification = DocumentEventBase & {
  method?: "document/saved";
};
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "DocumentClosed".
 */
export type DocumentClosedNotification = DocumentEventBase & {
  method?: "document/closed";
};
/**
 * A deleted document has an identity but no content: it carries no revision, unlike every other document event.
 *
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "DocumentDeleted".
 */
export type DocumentDeletedNotification = NotificationBase & {
  method?: "document/deleted";
  params?: {
    workspaceId: WorkspaceId;
    uri: string;
  };
};
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "DocumentRenamed".
 */
export type DocumentRenamedNotification = NotificationBase & {
  method?: "document/renamed";
  params?: {
    workspaceId: WorkspaceId;
    previousUri: string;
    document: DocumentReference;
  };
};
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "DiagnosticsChanged".
 */
export type DiagnosticsChangedNotification = NotificationBase & {
  method?: "diagnostics/changed";
  params?: {
    workspaceId: WorkspaceId;
    documentUri: string;
    revision: Revision;
  };
};
/**
 * Announces that a workspace trust level changed. Nothing else about the workspace is invalidated.
 *
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "WorkspaceTrustChanged".
 */
export type WorkspaceTrustChangedNotification = NotificationBase & {
  method?: "workspace/trustChanged";
  params?: {
    workspaceId: WorkspaceId;
    adapterId: AdapterId;
    trust: WorkspaceTrust;
  };
};

export interface IDEBPProtocolTypes {}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "InvalidRequest".
 */
export interface InvalidRequest {
  jsonrpc: "2.0";
  id: ResponseId;
  error: {
    code: -32600;
    message: string;
    data: {
      code: "INVALID_REQUEST";
      retryable: false;
    };
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "AuthenticationFailed".
 */
export interface AuthenticationFailed {
  jsonrpc: "2.0";
  id: ResponseId;
  error: {
    code: -32001;
    message: string;
    data: {
      code: "AUTHENTICATION_FAILED";
      retryable: false;
    };
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "UnsupportedProtocolVersion".
 */
export interface UnsupportedProtocolVersion {
  jsonrpc: "2.0";
  id: ResponseId;
  error: {
    code: -32002;
    message: string;
    data: {
      code: "UNSUPPORTED_PROTOCOL_VERSION";
      retryable: false;
      supportedProtocol: {
        minimum: IDEBPProtocolVersion;
        maximum: IDEBPProtocolVersion;
      };
    };
  };
}
/**
 * The first application message on every IDEBP WebSocket connection.
 *
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "HandshakeRequest".
 */
export interface BridgeHandshakeRequest {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  method: "bridge/handshake";
  params: {
    authentication: IDEBPHandshakeAuthentication;
    role: IDEBPSessionRole;
    /**
     * Inclusive protocol version range. The daemon additionally verifies that minimum is not greater than maximum.
     */
    protocol: {
      minimum: IDEBPProtocolVersion;
      maximum: IDEBPProtocolVersion;
    };
    topology: IDEBPEndpointTopology;
    clientInfo: {
      name: string;
      version: string;
    };
  };
}
/**
 * Authentication using the base64url token read from the private discovery file. A 32-byte token encodes to 43 base64url characters without padding.
 *
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "Authentication".
 */
export interface IDEBPHandshakeAuthentication {
  method: "token";
  token: AuthenticationToken;
}
/**
 * Describes where an endpoint runs and which source URI schemes it can see. URI mappings are explicit and are never inferred.
 *
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "Topology".
 */
export interface IDEBPEndpointTopology {
  hostKind: "local" | "remote-workspace" | "web" | "gateway";
  environmentKind:
    "local" | "ssh" | "wsl" | "dev-container" | "codespace" | "jetbrains-remote" | "unknown";
  /**
   * @minItems 1
   */
  uriSchemes: [string, ...string[]];
  uriMappings?: {
    sourceUriPrefix: string;
    targetUriPrefix: string;
    direction: "client-to-daemon" | "daemon-to-client" | "bidirectional";
  }[];
}
/**
 * Creates an authenticated, versioned IDEBP session and announces the daemon topology.
 *
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "HandshakeResponse".
 */
export interface BridgeHandshakeResponse {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  result: {
    sessionId: SessionId;
    role: IDEBPSessionRole;
    protocolVersion: IDEBPProtocolVersion;
    daemonInfo: {
      name: string;
      version: string;
    };
    topology: IDEBPEndpointTopology;
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "Adapter".
 */
export interface Adapter {
  adapterId: AdapterId;
  sessionId: SessionId;
  name: string;
  version: string;
  ideKind: "vscode" | "jetbrains";
  ideVersion: string;
  /**
   * @minItems 1
   */
  positionEncodings: [PositionEncoding, ...PositionEncoding[]];
  capabilities: Capabilities;
  connectedAt: string;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "Capabilities".
 */
export interface Capabilities {
  [k: string]: Capability;
}
/**
 * Capability dimensions are operation-dependent: guarantee describes semantic/syntactic quality, atomicity describes application behavior, and preview describes preparability. An omitted dimension is not applicable and must not be inferred.
 *
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "AvailableCapability".
 */
export interface AvailableCapability {
  support: "native" | "provider" | "adapter";
  guarantee?: Guarantee;
  preview?: boolean;
  atomicity?: Atomicity;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "UnavailableCapability".
 */
export interface UnavailableCapability {
  support: "unavailable";
  reason?: string;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "Session".
 */
export interface Session {
  sessionId: SessionId;
  role: IDEBPSessionRole;
  protocolVersion: IDEBPProtocolVersion;
  clientName: string;
  connectedAt: string;
  lastActivityAt: string;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "Diagnostic".
 */
export interface Diagnostic {
  range: Range;
  positionEncoding: PositionEncoding;
  severity: "error" | "warning" | "information" | "hint";
  message: string;
  source?: string;
  code?: string | number;
  relatedInformation?: {
    location: Location;
    message: string;
  }[];
  /**
   * Fixes the IDE offers for this diagnostic. Absent when none were offered; an empty array would claim the adapter looked and found nothing, which is a different statement.
   *
   * @maxItems 32
   */
  availableFixes?: AvailableFix[];
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "Range".
 */
export interface Range {
  start: Position;
  end: Position;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "Position".
 */
export interface Position {
  line: number;
  character: number;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "Location".
 */
export interface Location {
  uri: string;
  range: Range;
  positionEncoding: PositionEncoding;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "AvailableFix".
 */
export interface AvailableFix {
  /**
   * Opaque handle for this offer, valid for the snapshot that produced it. A consumer passes it back to prepare the fix; it is never a command the adapter interprets.
   */
  fixId: string;
  /**
   * The IDE's own wording for the fix, as a user would see it in the editor. Not interpreted, and never a language this adapter knows about.
   */
  title: string;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "DocumentDiagnostics".
 */
export interface DocumentDiagnostics {
  document: DocumentReference;
  diagnostics: Diagnostic[];
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "DocumentReference".
 */
export interface DocumentReference {
  workspaceId: WorkspaceId;
  rootId: RootId;
  uri: string;
  logicalPath?: string;
  revision: Revision;
  positionEncoding: PositionEncoding;
  languageId?: string;
  isDirty: boolean;
}
/**
 * Identity of a document's content. contentHash is the authoritative check; editorVersion is a fast path that exists only while the document is open in an editor.
 *
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "Revision".
 */
export interface Revision {
  /**
   * Present only when the document is open in an editor buffer. Absent means the content is the file on disk, which has no editor version — comparisons then rest on contentHash alone.
   */
  editorVersion?: number;
  contentHash: ContentHash;
  workspaceEpoch: number;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "DocumentContent".
 */
export interface DocumentContent {
  document: DocumentReference;
  text: string;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "ChangeSummary".
 */
export interface ChangeSummary {
  kind: "textEdit";
  uri: string;
  editCount: number;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "EditPlan".
 */
export interface EditPlan {
  planId: PlanId;
  adapterId: AdapterId;
  sessionId: SessionId;
  workspaceId: WorkspaceId;
  expiresAt: string;
  operation: EditOperation;
  guarantee: Guarantee;
  atomicity: Atomicity;
  /**
   * @minItems 1
   */
  preconditions: [DocumentRevisionPrecondition, ...DocumentRevisionPrecondition[]];
  /**
   * @minItems 1
   */
  changes: [ChangeSummary, ...ChangeSummary[]];
  warnings: string[];
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "DocumentRevisionPrecondition".
 */
export interface DocumentRevisionPrecondition {
  type: "documentRevision";
  uri: string;
  editorVersion?: number;
  contentHash: ContentHash;
  workspaceEpoch: number;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "ModifiedDocument".
 */
export interface ModifiedDocument {
  document: DocumentReference;
  beforeHash: ContentHash;
  afterHash: ContentHash;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "UndoToken".
 */
export interface UndoToken {
  id: UndoTokenId;
  adapterId: AdapterId;
  sessionId: SessionId;
  workspaceId: WorkspaceId;
  expiresAt?: string;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "WorkspaceStatus".
 */
export interface WorkspaceStatus {
  workspaceId: WorkspaceId;
  state: ReadinessState;
  capabilitiesUnavailable: string[];
  progress: Progress;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "SymbolHandle".
 */
export interface SymbolHandle {
  adapterId: AdapterId;
  sessionId: SessionId;
  id: SymbolHandleId;
  validUntilEpoch: number;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "SymbolLocator".
 */
export interface SymbolLocator {
  documentUri: string;
  name: string;
  qualifiedName?: string;
  kind: SymbolKind;
  /**
   * Opaque, adapter-defined token for the syntactic form of a declaration. Comparable only for equality, and only against locators minted by the same adapter. It exists so a stale symbol can be relocated without depending on 'kind', which not every IDE can supply.
   */
  declarationType?: string;
  containerName?: string;
  selectionRange: Range;
  positionEncoding: PositionEncoding;
  fingerprint: ContentHash;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "Symbol".
 */
export interface Symbol {
  handle: SymbolHandle;
  locator: SymbolLocator;
  range: Range;
  children: Symbol[];
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "SymbolLocation".
 */
export interface SymbolLocation {
  location: Location;
  symbol?: Symbol;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "WorkspaceRoot".
 */
export interface WorkspaceRoot {
  rootId: RootId;
  name: string;
  uri: string;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "Workspace".
 */
export interface Workspace {
  workspaceId: WorkspaceId;
  adapterId: AdapterId;
  name: string;
  /**
   * @minItems 1
   */
  roots: [WorkspaceRoot, ...WorkspaceRoot[]];
  workspaceEpoch: number;
  trust: WorkspaceTrust;
}
/**
 * Private local metadata used to discover and authenticate to one daemon instance.
 *
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "DiscoveryFile".
 */
export interface IDEBPDiscoveryFile {
  protocolVersion: IDEBPProtocolVersion;
  endpoint: string;
  token: AuthenticationToken;
  pid: number;
  startedAt: string;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "ErrorResponse".
 */
export interface IDEBPJSONRPCErrorResponse {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier | null;
  error: {
    code: -32600 | -32000 | -32001 | -32002;
    message: string;
    data: ErrorData;
  };
}
/**
 * This interface was referenced by `IDEBPJSONRPCErrorResponse`'s JSON-Schema
 * via the `definition` "genericErrorData".
 *
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "GenericErrorData".
 */
export interface GenericErrorData {
  code: GenericErrorCode;
  retryable: boolean;
  details?: ErrorDetails;
}
/**
 * This interface was referenced by `IDEBPJSONRPCErrorResponse`'s JSON-Schema
 * via the `definition` "errorDetails".
 *
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "ErrorDetails".
 */
export interface ErrorDetails {
  adapterId?: AdapterId;
  workspaceId?: WorkspaceId;
  documentUri?: string;
  planId?: PlanId;
  capability?: string;
  currentRevision?: Revision;
  /**
   * @minItems 2
   */
  candidates?: [SymbolLocator, SymbolLocator, ...SymbolLocator[]];
  /**
   * @minItems 1
   */
  modifiedDocuments?: [ModifiedDocument, ...ModifiedDocument[]];
  supportedProtocol?: {
    minimum: IDEBPProtocolVersion;
    maximum: IDEBPProtocolVersion;
  };
}
/**
 * This interface was referenced by `IDEBPJSONRPCErrorResponse`'s JSON-Schema
 * via the `definition` "indexNotReadyErrorData".
 *
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "IndexNotReadyErrorData".
 */
export interface IndexNotReadyErrorData {
  code: "INDEX_NOT_READY";
  retryable: true;
  details?: ErrorDetails;
}
/**
 * This interface was referenced by `IDEBPJSONRPCErrorResponse`'s JSON-Schema
 * via the `definition` "staleDocumentErrorData".
 *
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "StaleDocumentErrorData".
 */
export interface StaleDocumentErrorData {
  code: "STALE_DOCUMENT";
  retryable: boolean;
  details: {
    workspaceId?: WorkspaceId;
    documentUri?: string;
    currentRevision: Revision;
  };
}
/**
 * This interface was referenced by `IDEBPJSONRPCErrorResponse`'s JSON-Schema
 * via the `definition` "ambiguousSymbolErrorData".
 *
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "AmbiguousSymbolErrorData".
 */
export interface AmbiguousSymbolErrorData {
  code: "AMBIGUOUS_SYMBOL";
  retryable: boolean;
  details: {
    workspaceId?: WorkspaceId;
    documentUri?: string;
    /**
     * @minItems 2
     */
    candidates: [SymbolLocator, SymbolLocator, ...SymbolLocator[]];
  };
}
/**
 * This interface was referenced by `IDEBPJSONRPCErrorResponse`'s JSON-Schema
 * via the `definition` "partialApplyErrorData".
 *
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "PartialApplyErrorData".
 */
export interface PartialApplyErrorData {
  code: "PARTIAL_APPLY";
  retryable: boolean;
  details: {
    workspaceId?: WorkspaceId;
    planId?: PlanId;
    /**
     * @minItems 1
     */
    modifiedDocuments: [ModifiedDocument, ...ModifiedDocument[]];
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "AdministrationRequestBase".
 */
export interface AdministrationRequestBase {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  method: "bridge/getStatus" | "bridge/listAdapters" | "bridge/listSessions";
  params: {};
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "BridgeGetStatusResponse".
 */
export interface BridgeGetStatusResponse {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  result: {
    daemonVersion: string;
    protocol: {
      minimum: IDEBPProtocolVersion;
      maximum: IDEBPProtocolVersion;
    };
    startedAt: string;
    uptimeMs: number;
    adapterCount: number;
    workspaceCount: number;
    sessionCount: number;
    /**
     * Counters the daemon keeps about its own traffic. Optional: a daemon that keeps none omits the field rather than reporting zeroes, which would be indistinguishable from an idle daemon. Read-only, in-memory, reset by a restart (ADR-0035).
     */
    metrics?: {
      methods: {
        method: string;
        calls: number;
        refusals: number;
        p50: number;
        p95: number;
      }[];
      /**
       * Refusals per normalized error code, highest first.
       */
      refusals: {
        /**
         * The normalized error code counted. A string rather than the canonical enum on purpose: this is a histogram key, and a code a given version does not recognize should still be reported instead of invalidating the whole status response.
         */
        code: string;
        count: number;
      }[];
      /**
       * Responses that carried `truncated`, per method.
       */
      incomplete: {
        method: string;
        count: number;
      }[];
      /**
       * Recent queries consumers issued, newest first, from a capped in-memory ring. User text by nature: kept in memory only, never written to the structured log, and bounded by queryRingCapacity (ADR-0035).
       */
      queries: {
        query: string;
        method: string;
        at: number;
      }[];
      queryRingCapacity: number;
    };
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "BridgeListAdaptersResponse".
 */
export interface BridgeListAdaptersResponse {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  result: {
    adapters: Adapter[];
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "BridgeListSessionsResponse".
 */
export interface BridgeListSessionsResponse {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  result: {
    sessions: Session[];
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "DiagnosticsGetSnapshotRequest".
 */
export interface DiagnosticsGetSnapshotRequest {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  method: "diagnostics/getSnapshot";
  params: {
    workspaceId: WorkspaceId;
    documentUris?: string[];
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "DiagnosticsGetSnapshotResponse".
 */
export interface DiagnosticsGetSnapshotResponse {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  result: {
    documents: DocumentDiagnostics[];
    capturedAt: string;
    /**
     * True when the adapter holds diagnostics this snapshot does not carry: documents beyond a ceiling, or documents whose revision it cannot establish truthfully. False means the snapshot is complete for its requested scope.
     */
    truncated: boolean;
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "DocumentTargetParams".
 */
export interface DocumentTargetParams {
  workspaceId: WorkspaceId;
  uri: string;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "DocumentReadRequest".
 */
export interface DocumentReadRequest {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  method: "document/read";
  params: DocumentTargetParams;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "DocumentReadResponse".
 */
export interface DocumentReadResponse {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  result: DocumentContent;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "DocumentGetRevisionRequest".
 */
export interface DocumentGetRevisionRequest {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  method: "document/getRevision";
  params: DocumentTargetParams;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "DocumentGetRevisionResponse".
 */
export interface DocumentGetRevisionResponse {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  result: {
    document: DocumentReference;
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "DocumentGetSymbolsRequest".
 */
export interface DocumentGetSymbolsRequest {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  method: "document/getSymbols";
  params: DocumentTargetParams;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "DocumentGetSymbolsResponse".
 */
export interface DocumentGetSymbolsResponse {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  result: {
    document: DocumentReference;
    symbols: Symbol[];
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "RefactorPrepareRequest".
 */
export interface RefactorPrepareRequest {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  method: "refactor/prepare";
  params: {
    workspaceId: WorkspaceId;
    operation: EditOperation;
    /**
     * Document the operation applies to. Required for document-scoped operations such as reformat.
     */
    uri?: string;
    symbol?: SymbolReference;
    /**
     * Operation-specific values, such as a new name or an extracted method's name. Deliberately open: what an operation needs is the IDE's business, and constraining it here would prevent adapters exposing refactorings this schema never anticipated.
     */
    arguments?: {
      [k: string]: string;
    };
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "RefactorPrepareResponse".
 */
export interface RefactorPrepareResponse {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  result: {
    plan: EditPlan;
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "RefactorPrepareRenameRequest".
 */
export interface RefactorPrepareRenameRequest {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  method: "refactor/prepareRename";
  params: {
    workspaceId: WorkspaceId;
    symbol: SymbolReference;
    newName: string;
    options: {
      includeComments: boolean;
      includeStrings: boolean;
    };
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "RefactorPrepareRenameResponse".
 */
export interface RefactorPrepareRenameResponse {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  result: {
    plan: EditPlan;
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "WorkspaceApplyPlanRequest".
 */
export interface WorkspaceApplyPlanRequest {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  method: "workspace/applyPlan";
  params: ApplyPlanParams;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "ApplyPlanParams".
 */
export interface ApplyPlanParams {
  workspaceId: WorkspaceId;
  planId: PlanId;
  includePostApplyDiagnostics?: boolean;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "WorkspaceApplyPlanResponse".
 */
export interface WorkspaceApplyPlanResponse {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  result: ModificationResult;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "ModificationResult".
 */
export interface ModificationResult {
  /**
   * @minItems 1
   */
  modifiedDocuments: [ModifiedDocument, ...ModifiedDocument[]];
  undoToken?: UndoToken;
  diagnostics?: DocumentDiagnostics[];
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "WorkspaceDiscardPlanRequest".
 */
export interface WorkspaceDiscardPlanRequest {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  method: "workspace/discardPlan";
  params: PlanIdParams;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "PlanIdParams".
 */
export interface PlanIdParams {
  workspaceId: WorkspaceId;
  planId: PlanId;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "WorkspaceDiscardPlanResponse".
 */
export interface WorkspaceDiscardPlanResponse {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  result: {
    planId: PlanId;
    discarded: true;
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "WorkspaceUndoRequest".
 */
export interface WorkspaceUndoRequest {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  method: "workspace/undo";
  params: {
    workspaceId: WorkspaceId;
    undoToken: UndoToken;
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "WorkspaceUndoResponse".
 */
export interface WorkspaceUndoResponse {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  result: ModificationResult;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "IdeRegisterRequest".
 */
export interface IdeRegisterRequest {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  method: "ide/register";
  params: {
    adapterId: AdapterId;
    name: string;
    version: string;
    ideKind: "vscode" | "jetbrains";
    ideVersion: string;
    /**
     * @minItems 1
     */
    positionEncodings: [PositionEncoding, ...PositionEncoding[]];
    capabilities: Capabilities;
    workspaces: Workspace[];
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "IdeRegisterResponse".
 */
export interface IdeRegisterResponse {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  result: {
    adapter: Adapter;
    workspaces: Workspace[];
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "IdeUnregisterRequest".
 */
export interface IdeUnregisterRequest {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  method: "ide/unregister";
  params: {
    adapterId: AdapterId;
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "IdeUnregisterResponse".
 */
export interface IdeUnregisterResponse {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  result: {
    adapterId: AdapterId;
    unregistered: true;
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "IdePingRequest".
 */
export interface IdePingRequest {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  method: "ide/ping";
  params: {
    sentAt: string;
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "IdePingResponse".
 */
export interface IdePingResponse {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  result: {
    sentAt: string;
    receivedAt: string;
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "IdeGetCapabilitiesRequest".
 */
export interface IdeGetCapabilitiesRequest {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  method: "ide/getCapabilities";
  params: {
    adapterId: AdapterId;
    workspaceId?: WorkspaceId;
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "IdeGetCapabilitiesResponse".
 */
export interface IdeGetCapabilitiesResponse {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  result: {
    adapterId: AdapterId;
    workspaceId?: WorkspaceId;
    capabilities: Capabilities;
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "SymbolTargetParams".
 */
export interface SymbolTargetParams {
  workspaceId: WorkspaceId;
  symbol: SymbolReference;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "WorkspaceSearchSymbolsRequest".
 */
export interface WorkspaceSearchSymbolsRequest {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  method: "workspace/searchSymbols";
  params: {
    workspaceId: WorkspaceId;
    query: string;
    /**
     * @maxItems 27
     */
    kinds?: SymbolKind[];
    limit?: number;
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "WorkspaceSearchSymbolsResponse".
 */
export interface WorkspaceSearchSymbolsResponse {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  result: {
    symbols: Symbol[];
    truncated: boolean;
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "SymbolResolveAtRequest".
 */
export interface SymbolResolveAtRequest {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  method: "symbol/resolveAt";
  params: {
    workspaceId: WorkspaceId;
    uri: string;
    position: Position;
    positionEncoding: PositionEncoding;
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "SymbolResolveAtResponse".
 */
export interface SymbolResolveAtResponse {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  result: {
    document: DocumentReference;
    symbol?: Symbol1;
  };
}
/**
 * Omitted when no symbol covers the requested position, which is an ordinary outcome for a blank line or a comment rather than an error.
 */
export interface Symbol1 {
  handle: SymbolHandle;
  locator: SymbolLocator;
  range: Range;
  children: Symbol[];
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "SymbolLookupRequestBase".
 */
export interface SymbolLookupRequestBase {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  method: "symbol/getDefinition" | "symbol/getReferences" | "symbol/getImplementations";
  params: SymbolTargetParams;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "SymbolGetDefinitionResponse".
 */
export interface SymbolGetDefinitionResponse {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  result: {
    locations: SymbolLocation[];
    /**
     * True when the adapter had more in-scope locations than it returned. These requests carry no limit parameter, so the ceiling is fixed and this flag is the only way a consumer can tell a complete answer from a capped one.
     */
    truncated: boolean;
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "SymbolGetReferencesResponse".
 */
export interface SymbolGetReferencesResponse {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  result: {
    locations: SymbolLocation[];
    /**
     * True when the adapter had more in-scope locations than it returned. These requests carry no limit parameter, so the ceiling is fixed and this flag is the only way a consumer can tell a complete answer from a capped one.
     */
    truncated: boolean;
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "SymbolGetImplementationsResponse".
 */
export interface SymbolGetImplementationsResponse {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  result: {
    locations: SymbolLocation[];
    /**
     * True when the adapter had more in-scope locations than it returned. These requests carry no limit parameter, so the ceiling is fixed and this flag is the only way a consumer can tell a complete answer from a capped one.
     */
    truncated: boolean;
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "SymbolLocationsResponseBase".
 */
export interface SymbolLocationsResponseBase {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  result: {
    locations: SymbolLocation[];
    /**
     * True when the adapter had more in-scope locations than it returned. These requests carry no limit parameter, so the ceiling is fixed and this flag is the only way a consumer can tell a complete answer from a capped one.
     */
    truncated: boolean;
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "SymbolHierarchyParams".
 */
export interface SymbolHierarchyParams {
  workspaceId: WorkspaceId;
  symbol: SymbolReference;
  /**
   * Which neighbours to return. Named for the relation rather than a direction so that a consumer never has to know whether an IDE models 'up' as supertypes or callers.
   */
  relation: "callers" | "callees" | "supertypes" | "subtypes";
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "SymbolGetHierarchyRequest".
 */
export interface SymbolGetHierarchyRequest {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  method: "symbol/getHierarchy";
  params: SymbolHierarchyParams;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "SymbolGetHierarchyResponse".
 */
export interface SymbolGetHierarchyResponse {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  result: {
    locations: SymbolLocation[];
    /**
     * True when the adapter had more in-scope locations than it returned. These requests carry no limit parameter, so the ceiling is fixed and this flag is the only way a consumer can tell a complete answer from a capped one.
     */
    truncated: boolean;
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "WorkspaceListRequest".
 */
export interface WorkspaceListRequest {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  method: "workspace/list";
  params: {
    adapterId?: AdapterId;
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "WorkspaceListResponse".
 */
export interface WorkspaceListResponse {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  result: {
    workspaces: Workspace[];
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "WorkspaceGetRequest".
 */
export interface WorkspaceGetRequest {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  method: "workspace/get";
  params: WorkspaceIdParams;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "WorkspaceIdParams".
 */
export interface WorkspaceIdParams {
  workspaceId: WorkspaceId;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "WorkspaceGetResponse".
 */
export interface WorkspaceGetResponse {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  result: {
    workspace: Workspace;
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "WorkspaceGetStatusRequest".
 */
export interface WorkspaceGetStatusRequest {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  method: "workspace/getStatus";
  params: WorkspaceIdParams;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "WorkspaceGetStatusResponse".
 */
export interface WorkspaceGetStatusResponse {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  result: {
    status: WorkspaceStatus;
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "TodoItem".
 */
export interface TodoItem {
  location: Location;
  /**
   * The marker's own text, as the author wrote it. Bounded because a malformed comment can run to the length of a file.
   */
  text: string;
  /**
   * Which of the IDE's configured patterns matched — TODO, FIXME, or whatever the user added. Opaque: the adapter never interprets it.
   */
  pattern?: string;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "WorkspaceSearchTodosRequest".
 */
export interface WorkspaceSearchTodosRequest {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  method: "workspace/searchTodos";
  params: {
    workspaceId: WorkspaceId;
    /**
     * Restrict to one document. Omitted, the search spans every registered root — which is what an agent surveying a codebase wants.
     */
    uri?: string;
    limit?: number;
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "WorkspaceSearchTodosResponse".
 */
export interface WorkspaceSearchTodosResponse {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  result: {
    /**
     * @maxItems 1000
     */
    items: TodoItem[];
    /**
     * True when the IDE had more markers than were returned. An empty list with this false means the IDE looked and found none.
     */
    truncated: boolean;
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "Bookmark".
 */
export interface Bookmark {
  location: Location;
  /**
   * The note the user attached, when they attached one. Absent, not empty, when they did not.
   */
  description?: string;
  /**
   * The user's own grouping, as the IDE names it. Opaque: never interpreted here.
   */
  group?: string;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "WorkspaceListBookmarksRequest".
 */
export interface WorkspaceListBookmarksRequest {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  method: "workspace/listBookmarks";
  params: {
    workspaceId: WorkspaceId;
    limit?: number;
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "WorkspaceListBookmarksResponse".
 */
export interface WorkspaceListBookmarksResponse {
  jsonrpc: "2.0";
  id: JSONRPCRequestIdentifier;
  result: {
    /**
     * @maxItems 1000
     */
    bookmarks: Bookmark[];
    /**
     * True when the IDE held more bookmarks than were returned. An empty list with this false means the user has none.
     */
    truncated: boolean;
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "CancelRequest".
 */
export interface CancelRequestNotification {
  jsonrpc: "2.0";
  method: "$/cancelRequest";
  params: {
    id: JSONRPCRequestIdentifier;
  };
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "NotificationBase".
 */
export interface NotificationBase {
  jsonrpc: "2.0";
  method: string;
  params: unknown;
}
/**
 * This interface was referenced by `IDEBPProtocolTypes`'s JSON-Schema
 * via the `definition` "WorkspaceIdentityParams".
 */
export interface WorkspaceIdentityParams {
  workspaceId: WorkspaceId;
  adapterId: AdapterId;
}
