import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { compile } from "json-schema-to-typescript";
import type { JSONSchema, Options } from "json-schema-to-typescript";
import { format, resolveConfig } from "prettier";

interface SchemaDocument extends Record<string, unknown> {
  $id?: string;
  $defs?: Record<string, unknown>;
}

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const protocolDirectory = join(repositoryRoot, "packages", "protocol");
const schemasDirectory = join(protocolDirectory, "schemas");
const outputPath = join(protocolDirectory, "src", "generated.ts");
const schemaIdPrefix = "https://ide-bridge.dev/schemas/0.1.0/";

function readJson(path: string): SchemaDocument {
  return JSON.parse(readFileSync(path, "utf8")) as SchemaDocument;
}

function listJsonFiles(directory: string): string[] {
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const path = join(directory, entry.name);
    return entry.isDirectory() ? listJsonFiles(path) : entry.name.endsWith(".json") ? [path] : [];
  });
}

function toPascalCase(value: string): string {
  return value
    .replace(/\.schema$/u, "")
    .split(/[^A-Za-z0-9]+/u)
    .filter((part) => part.length > 0)
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join("");
}

function hasTopLevelContract(schema: SchemaDocument): boolean {
  return ["type", "oneOf", "anyOf", "allOf", "$ref"].some((keyword) => keyword in schema);
}

const schemas = listJsonFiles(schemasDirectory).map((path) => ({ path, schema: readJson(path) }));
const schemasById = new Map<string, SchemaDocument>();
const generatedDefinitions: Record<string, JSONSchema> = {};

function addGeneratedDefinition(name: string, reference: string): void {
  if (name in generatedDefinitions) {
    throw new Error(`Generated protocol type name is duplicated: ${name}`);
  }
  generatedDefinitions[name] = { $ref: reference };
}

for (const { path, schema } of schemas) {
  if (schema.$id === undefined) {
    throw new Error(`Protocol schema has no $id: ${relative(repositoryRoot, path)}`);
  }
  if (!schema.$id.startsWith(schemaIdPrefix)) {
    throw new Error(`Protocol schema has an unexpected $id: ${schema.$id}`);
  }

  schemasById.set(schema.$id, schema);

  if (hasTopLevelContract(schema)) {
    const fileName = path.slice(path.lastIndexOf("/") + 1, -".json".length);
    addGeneratedDefinition(toPascalCase(fileName), schema.$id);
  }

  for (const definitionName of Object.keys(schema.$defs ?? {})) {
    addGeneratedDefinition(toPascalCase(definitionName), `${schema.$id}#/$defs/${definitionName}`);
  }
}

const generationRoot: JSONSchema = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  title: "IDEBPProtocolTypes",
  type: "object",
  additionalProperties: false,
  definitions: generatedDefinitions,
};

const referenceOptions = {
  resolve: {
    idebp: {
      order: 1,
      canRead: /^https:\/\/ide-bridge\.dev\/schemas\/0\.1\.0\//u,
      read(file: { url: string }): string {
        const [schemaId] = file.url.split("#", 1);
        if (schemaId === undefined) {
          throw new Error(`Referenced protocol schema URL is invalid: ${file.url}`);
        }
        const schema = schemasById.get(schemaId);
        if (schema === undefined) {
          throw new Error(`Referenced protocol schema is not registered: ${file.url}`);
        }
        return JSON.stringify(schema);
      },
    },
    http: false,
  },
} as unknown as Options["$refOptions"];

const generated = await compile(generationRoot, "IDEBPProtocolTypes", {
  $refOptions: referenceOptions,
  additionalProperties: false,
  bannerComment:
    "/* eslint-disable */\n/**\n * AUTO-GENERATED by scripts/generate-types.ts.\n * JSON Schema 2020-12 files in packages/protocol/schemas are canonical.\n * Do not edit this file manually.\n */",
  declareExternallyReferenced: true,
  customName(schema, keyNameFromDefinition) {
    if (typeof schema.title === "string") {
      return toPascalCase(schema.title);
    }
    return keyNameFromDefinition === undefined ? undefined : toPascalCase(keyNameFromDefinition);
  },
  enableConstEnums: false,
  format: true,
  strictIndexSignatures: false,
  unknownAny: true,
  unreachableDefinitions: true,
});
const prettierOptions = (await resolveConfig(outputPath)) ?? {};
const formattedGenerated = await format(generated, {
  ...prettierOptions,
  filepath: outputPath,
});

if (process.argv.includes("--check")) {
  const current = readFileSync(outputPath, "utf8");
  if (current !== formattedGenerated) {
    throw new Error("Generated protocol types are stale. Run `pnpm protocol:generate`.");
  }
} else {
  writeFileSync(outputPath, formattedGenerated, "utf8");
  console.log(
    `Generated ${relative(repositoryRoot, outputPath)} from ${String(schemas.length)} schemas.`,
  );
}
