/**
 * Writes the `updatePlugins.xml` a JetBrains IDE polls to decide whether an update exists.
 *
 * A plugin installed from a zip has no update path: the IDE does not know where the file came from,
 * so it can never tell anyone a newer one was released. A custom plugin repository is the platform's
 * own answer — a static XML the user adds once under *Settings → Plugins → ⚙ → Manage Plugin
 * Repositories*, after which the IDE's usual update badge does the work. No Marketplace review, no
 * account, and nothing in the plugin that reaches the network.
 *
 * Generated from the built artefact rather than written by hand, because a repository file that
 * disagrees with the zip it points at is worse than none: the IDE offers an update, downloads it,
 * and installs a version that is not the one advertised.
 */

import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const REPOSITORY_ROOT = join(import.meta.dirname, "..");
const PLUGIN_ID = "com.idebridge.jetbrains";

interface Options {
  /** Where the zip will be reachable from. Releases are the obvious host; anything HTTP serves. */
  readonly baseUrl: string;
  readonly output: string;
}

function parseArguments(argv: readonly string[]): Options {
  const value = (flag: string, fallback: string): string => {
    const index = argv.indexOf(flag);
    return index >= 0 && argv[index + 1] !== undefined ? (argv[index + 1] as string) : fallback;
  };
  const version = readFileSync(join(REPOSITORY_ROOT, "VERSION"), "utf8").trim();
  return {
    baseUrl: value("--base-url", `https://github.com/Zall9/junon/releases/download/v${version}`),
    output: value("--out", join(REPOSITORY_ROOT, "build", "updatePlugins.xml")),
  };
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function main(): void {
  const options = parseArguments(process.argv.slice(2));
  const version = readFileSync(join(REPOSITORY_ROOT, "VERSION"), "utf8").trim();

  // The `since-build` in the XML is what the IDE checks before offering the update, so it is read
  // from the same place the plugin declares it rather than repeated here.
  const properties = readFileSync(
    join(REPOSITORY_ROOT, "jetbrains-plugin", "gradle.properties"),
    "utf8",
  );
  const sinceBuild = /^pluginSinceBuild=(.+)$/m.exec(properties)?.[1]?.trim();
  const pluginName = /^pluginName=(.+)$/m.exec(properties)?.[1]?.trim();
  if (sinceBuild === undefined || pluginName === undefined) {
    throw new Error("gradle.properties no longer declares pluginSinceBuild and pluginName");
  }

  const declaredVersion = /^pluginVersion=(.+)$/m.exec(properties)?.[1]?.trim();
  if (declaredVersion !== version) {
    // The whole point of generating this file is that it agrees with the artefact.
    throw new Error(
      `VERSION says ${version} and gradle.properties says ${declaredVersion}; ` +
        "the repository file would advertise a version nobody built",
    );
  }

  const archive = join(
    REPOSITORY_ROOT,
    "jetbrains-plugin",
    "build",
    "distributions",
    `${pluginName}-${version}.zip`,
  );
  let size: number;
  let sha256: string;
  try {
    size = statSync(archive).size;
    sha256 = createHash("sha256").update(readFileSync(archive)).digest("hex");
  } catch {
    throw new Error(
      `${archive} is missing. Run \`cd jetbrains-plugin && ./gradlew buildPlugin\` first: this file ` +
        "describes an artefact, and describing one that does not exist is how a repository starts " +
        "lying.",
    );
  }

  const url = `${options.baseUrl.replace(/\/$/, "")}/${pluginName}-${version}.zip`;
  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/make-update-repository.ts from the built artefact. Do not edit by hand. -->
<plugins>
  <plugin id="${escapeXml(PLUGIN_ID)}" url="${escapeXml(url)}" version="${escapeXml(version)}">
    <idea-version since-build="${escapeXml(sinceBuild)}"/>
    <name>IDE Bridge</name>
    <description><![CDATA[Answers an agent's questions from this IDE's own indexes, analysers and refactoring engines, over an authenticated loopback connection.]]></description>
  </plugin>
</plugins>
`;

  mkdirSync(dirname(options.output), { recursive: true });
  writeFileSync(options.output, xml, "utf8");
  process.stdout.write(
    `${options.output}\n  plugin  ${PLUGIN_ID} ${version} (since-build ${sinceBuild})\n` +
      `  points at ${url}\n  artefact ${size} bytes, sha256 ${sha256.slice(0, 16)}…\n`,
  );
}

main();
